site_name: Escoteirando

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        enabled: false

  - search:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      # js_files:
      #   - assets/js/main.js
      # css_files:
      #   - assets/css/style.css

theme:
  name: windmill

markdown_extensions:
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_div_format"
        - name: arithmatex
          class: arithmatex
