@startuml escoteirando_portal_uc
left to right direction
:Escotista: as escotista

package Acesso {
usecase (Login) as login
usecase (Logout) as logout
}
package UE {
    usecase (Dados do\nGrupo Escoteiro) as dados_ge
usecase (Dados da\nseção) as dados_secao
usecase (Dados da\nsubseção) as dados_subsecao
usecase (Dados do\njovem) as dados_jovem
}
dados_ge --|> login
dados_secao --|> login
dados_subsecao --|> login
dados_jovem --|> login

package "Business Inteligence" {
    usecase (Timeline de conquistas\nda seção) as timeline_secao
    usecase (Timeline de conquistas\ndo jovem) as timeline_jovem
    usecase (Análise Histórica\ndo jovem) as analise_historica_jovem
}
timeline_secao --|> login
timeline_jovem --|> login
analise_historica_jovem --|> login

package "Banco de dados de atividades" {    
    usecase (Cadastro de\natividades) as cadastro_atividades
    usecase (Cadastro de\nencontros) as cadastro_encontros        
    usecase (Ferramenta de\nbusca) as ferramenta_busca
    usecase (Sistema de \npontuação) as sistema_pontuacao
}
cadastro_atividades --|> login
cadastro_encontros --|> login
ferramenta_busca --|> login
sistema_pontuacao --|> login

escotista --> login
escotista --> logout

escotista --> dados_ge
escotista --> dados_secao
escotista --> dados_subsecao
escotista --> dados_jovem

escotista --> timeline_secao
escotista --> timeline_jovem
escotista --> analise_historica_jovem

escotista --> cadastro_atividades
escotista --> cadastro_encontros
escotista --> ferramenta_busca
escotista --> sistema_pontuacao
@enduml